# Generated by Django 4.2.16 on 2024-10-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.TextField()),
                ("lastName", models.TextField()),
                ("city", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
    ]
